version: '3.4'

services:
  ltw.resources.api:
    image: ${DOCKER_REGISTRY-}ltwresourcesapi
    build:
      context: .
      dockerfile: Services/Resources/LTW.Resources.API/Dockerfile

  ltw.payment.api:
    image: ${DOCKER_REGISTRY-}ltwpaymentapi
    build:
      context: .
      dockerfile: Services/Payment/LTW.Payment.API/Dockerfile


  ltw.organization.api:
    image: ${DOCKER_REGISTRY-}ltworganizationapi
    build:
      context: .
      dockerfile: Services/Organization/LTW.Organization.API/Dockerfile


  ltw.incident.azurefunction:
    image: ${DOCKER_REGISTRY-}ltwincidentazurefunction
    build:
      context: .
      dockerfile: Services/Incident/LTW.Incident.AzureFunction/Dockerfile

